# application.yml - the configuration file for the Brill Server.
#
# Passwords should be supplied using system environemnt variables rather than entered directly. The system
# environment variables need to be setup in the OS runtime environment, otherwise the server won't start. 
#
---
spring:
   config.activate.on-profile: local
   application:
      name: brill_server
server:
   port: 8080
   allowedOrigins: "*"
   botsWebsite: true
   sessionsDirectory: sessions
database:
   driver: com.mysql.cj.jdbc.Driver
   url: jdbc:mysql://localhost:3306/brill_local_db?serverTimezone=UTC
   username: ${BRILL_LOCAL_DATABASE_USERNAME}
   password: ${BRILL_LOCAL_DATABASE_PWD}
brill.apps:
   #repo: git@bitbucket.org:brill-software/brill_apps.git
   repo: git@bitbucket.org:brill-software/brill_apps_fork.git
   local.repo:
      dir: ../brill_workspace
      skip.pull: false
passwords.pepper: ${BRILL_LOCAL_PWDS_PEPPER}
passwords.allowClearText: true
permissions.default: db_write,chatbot
log.sessions.to.db: false
chatbot:
   api.key: ${BRILL_LOCAL_CHATBOT_API_KEY}
   api.url: https://api.openai.com/v1/chat/completions
   model: gpt-4
   timeout: 120
logging:
    level:
        web: INFO
        brill: TRACE

---
spring:
   config.activate.on-profile: prod
   application:
      name: brill_server
server:
   port: 443
   extraHttpPort: 80
   redirectHttpToHttps: true
   allowedOrigins:
   botsWebsite: true
   sessionsDirectory: sessions
   ssl: 
      key-alias: tomcat
      key-store: ${BRILL_PROD_SERVER_SSL_KEY_STORE}
      key-store-password: ${BRILL_PROD_SERVER_SSL_KEY_STORE_PWD}
      key-store-provider: SUN
      key-store-type: JKS
database:
   driver: com.mysql.cj.jdbc.Driver
   url: jdbc:mysql://localhost:3306/brill_prod_db?serverTimezone=UTC
   username: ${BRILL_PROD_DATABASE_USERNAME}
   password: ${BRILL_PROD_DATABASE_PWD}    
brill.apps:
#    repo: git@bitbucket.org:brill-software/brill_apps.git
    repo: git@bitbucket.org:brill-software/brill_apps_fork.git
    local.repo.dir: BrillAppsRepo  
passwords.pepper: ${BRILL_PROD_PWDS_PEPPER}
passwords.allowClearText: true
permissions.default: db_write,chatbot
log.sessions.to.db: true
chatbot:
   api.key: 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
   # api_key: ${BRILL_PROD_CHATBOT_API_KEY}
   api.url: https://api.openai.com/v1/chat/completions
   model: gpt-4
   timeout: 120
logging:
    level:
        web: INFO
        brill: INFO